### ISSUE TITLE
Research web UI frameworks

### ISSUE THREAD

**Issue by chungha** [chungha/q-box#3]
We decided to use Web UI so need to make a decision for which framework is the best to us.
Let me find famous and brand-new frameworks and compare them.

**Comment by David-Cho** [comment]
그 Frame work라는 것이 문제를 만드는 틀을 말씀하시는 거죠?
 
 
-----Original Message-----

**Comment by David-Cho** [comment]
Is Framework is a kind of tool of making a quiz?

**Comment by chungha** [comment]
No. It's just a programming tool to build graphic user interface on
web-browser which shows a quiz and provides an input method to let a user
choose an answer.

**Comment by chungha** [comment]
Let's use 'React' made by Facebook. The reason why I chose was just that it's famous and brand-new :)

**Comment by chungha** [comment]
Here is the tutorial.
https://facebook.github.io/react/tutorial/tutorial.html

**Comment by chungha** [comment]
@chongho 
You can code ReactJS in CodePen.io like this.
http://codepen.io/gaearon/pen/rrpgNB?editors=0010
